  # Copyright 2025 Chainguard, Inc.
  # SPDX-License-Identifier: Apache-2.0

  issuer: https://token.actions.githubusercontent.com
  subject: repo:chainguard-dev/stigs:ref:refs/heads/main
  claim_pattern:
    job_workflow_ref: chainguard-dev/stigs/.github/workflows/update-ca-cert.yaml@refs/heads/main

  permissions:
    contents: write
    pull_requests: write
